- optimiser: 
          - Adam
  learning_rate: 
          - 0.0001
          - 0.0005
          - 0.001
          - 0.002
  width:
        - 64
        - 32
  depth: 6
- optimiser: Adam
  learning_rate: 0.001
  width: 5
  depth: 5